function p = getAudapterParamSet()
p = struct;

paramNames = {'bShift',     'bTrack',       'bDetect',      'bWeight', ...
              'bCepsLift',  'bRatioShift',  'bMelShift',    'bGainAdapt', ...
              'bRMSClip',   'bBypassFmt',   'bPitchShift',  'bShift2D', ...
              'bDownSampFilt', 'mute', ...
              'sRate',      'frameLen',     'nDelay',       'nWin', ...
              'nLPC',       'nFmts',        'nTracks',      'avgLen', ...
              'cepsWinWidth', 'fb',         'minVowelLen',  'pvocFrameLen', ...
              'pvocHop',    'nfb',          'tsgNTones',    'downFact', ...
              'stereoMode', ...
              'pvocAmpNormTrans', 'delayFrames', ...
              'scale',      'preemp',       'rmsThr',       'rmsRatio', ...
              'rmsFF',      'dFmtsFF',      'rmsClipThresh', 'wgFreq', ...
              'wgAmp',      'wgTime',       'f1Min',        'f1Max', ...
              'f2Min',      'f2Max',        'LBk',          'LBb', ...
              'trialLen',   'rampLen',      'aFact',        'bFact', ...
              'gFact',      'fn1',          'fn2',          'pitchShiftRatio', ...
              'rmsFF_fb',   'fb4GainDB',    'fb3Gain',      'fb2Gain', ...
              'datapb',     'pertF1',       'pertF2',       'pertAmp', ...
              'pertAmp2D',  'pertPhi',      'pertPhi2D',    'gain', ...
              'tsgToneDur', 'tsgToneFreq',  'tsgToneAmp',   'tsgToneRamp', ...
              'tsgInt', ...
              'bClampFormants','clamposts', 'clampf1'       'clampf2'};

% TODO: datapb length

for i1 = 1 : numel(paramNames)
    pn = paramNames{i1};

    p.(pn) = Audapter('getParam', pn);
end

% Add parameters introduced in version b2.5. If Audapter mex file doesn't
% have these parameters because it's an older version, they'll be skipped
paramNames_version_b2point5 = {'fb5GainDB_speech', 'fb5Gain_playback'};
for i1 = 1 : numel(paramNames_version_b2point5)
    pn = paramNames_version_b2point5{i1};
    try
        p.(pn) = Audapter('getParam', pn);
    catch
    end
end

% --- Aliased paramters --- %
p.rmsThresh = p.rmsThr;
p.sr = p.sRate;

return